config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :profile, to: 'users#profile'
  resources :pitches do
    get :video, to: 'pitches#video'
    get :random, to: 'pitches#random'
    resources :feedbacks, shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :masterpitch, optional: true

  has_many :feedbacks, dependent: :destroy

end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: [:show, :edit, :update, :destroy]

  def index
    @pitches = Pitch.all
    # @users = Pitch.where(id: @pitch.user_ids)
  end

  def show
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = Pitch.new(pitch_params)
    @pitch.user_id = current_user.id
    if @pitch.save
      redirect_to pitch_random_path(@pitch)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pitch.update(pitch_params)

    redirect_to pitch_path(@pitch)
  end

  def destroy
      @pitch.destroy
      respond_to do |format|
      format.html { redirect_to pitches_url, notice: "#{@pitch.name} was deleted." }
    end
  end

  def video
    @pitch = @pitch = Pitch.find(params[:pitch_id])
  end

private
  def set_pitch
    @pitch = Pitch.find(params[:id])
  end

  def pitch_params
    params.require(:pitch).permit(:name, :topic, :duration, :target, :transcript, :photo)
  end
end

app/views/pitches/_feedback_present.html.erb
<% @pitch.feedbacks.each do |feedback| %>
  <div class="col col-sm-6 col-xs-12">
    <div class="feedbackcard ">
      <div class="avatarfeedback">
        <%= image_tag user_avatar(current_user), class: "img-round" %>
        <div class="infoname">
          <h2><%= feedback.user.first_name %> <%= feedback.user.last_name %></h2>
          <h3> Pitch Expert</h3>
          <%= link_to 'Edit',    edit_feedback_path(feedback)  %>
          <%= link_to 'Delete', feedback_path(feedback), method: :delete %>
        </div>
      </div>
      <div class="tabs2">
        <a class="tab " id="quality-tab" data-toggle="tab" href="#quality" role="tab" aria-controls="home" aria-selected="true">
          <div class="col col-xs-12 col-sm-12">
            <h4>Quality</h4>
            <% feedback.quality.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </a>
        <a class="tab" id="value-tab" data-toggle="tab" href="#value" role="tab" aria-controls="profile" aria-selected="false" >
          <div class="col col-xs-12 col-sm-12">
            <div class="rating-column">
              <h4>Value</h4>
              <% feedback.value.times do  %>
                <i class="fa fa-star"></i>
              <% end %>
            </div>
          </div>
        </a>
        <a class="tab " id="clarity-tab" data-toggle="tab" href="#clarity" role="tab" aria-controls="home" aria-selected="true">
          <div class="col col-xs-12 col-sm-12">
            <h4>Clarity</h4>
            <% feedback.clarity.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </a>
        <a class="tab " id="pace-tab" data-toggle="tab" href="#pace" role="tab" aria-controls="home" aria-selected="true">
          <div class="col col-xs-12 col-sm-12">
            <h4>Pace</h4>
            <% feedback.pace.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </a>
        <a class="tab " id="body-tab" data-toggle="tab" href="#body" role="tab" aria-controls="home" aria-selected="true">
          <div class="col col-xs-12 col-sm-12">
            <h4>Body</h4>
            <% feedback.body_language.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </a>
        <a class="tab " id="language-tab" data-toggle="tab" href="#language" role="tab" aria-controls="home" aria-selected="true">
          <div class="col col-xs-12 col-sm-12">
            <h4>Language</h4>
            <% feedback.language.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </a>
      </div>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fadetext-center" id="quality" role="tabpanel" aria-labelledby="quality-tab">
          <% if feedback.quality_comment.present? %>
            <h5> <strong>Quality</strong> </h5>
            <p><%= feedback.quality_comment%>  </p>
          </li>
        <% end %>
      </div>
      <div class="tab-pane fade  text-center" id="value" role="tabpanel" aria-labelledby="value-tab">
        <% if feedback.value_comment.present? %>
          <h5> <strong> Value</strong>  </h5>
          <p> <%= feedback.value_comment%> </p>
        <% end %>
      </div>
      <div class="tab-pane fade text-center" id="clarity" role="tabpanel" aria-labelledby="clarity-tab">
        <% if feedback.clarity_comment.present? %>
          <h5> <strong>Clarity</strong>  </h5>
          <p> <%= feedback.clarity_comment%> </p>
        <% end %>
      </div>
      <div class="tab-pane fade text-center" id="pace" role="tabpanel" aria-labelledby="pace-tab">
        <% if feedback.pace_comment.present? %>
          <h5> <strong>Pace</strong> </h5>
          <p> <%= feedback.pace_comment%>  </p>
        <% end %>
      </div>
      <div class="tab-pane fade text-center" id="body" role="tabpanel" aria-labelledby="body-tab">
        <% if feedback.body_language_comment.present? %>
          <h5> <strong>Body Language</strong> </h5>
          <p> <%= feedback.body_language_comment%> </p>
        <% end %>
      </div>
      <div class="tab-pane fade text-center" id="language" role="tabpanel" aria-labelledby="language-tab">
        <% if feedback.language_comment.present? %>
          <h5>  <strong>Language</strong> </h5>
          <p> <%= feedback.language_comment%>  </p>
        <% end %>
      </div>
    </div>
    <div class="text-center" id=addfeedback>
      <% if feedback.comment.present? %>
        <h5>  <strong>Additional feedback</strong> </h5>
        <p><%= feedback.comment%>  </p>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/pitches/_no_feedback.html.erb
 <div class="text-center">
        <h3>
          There is no feedbacks for this pitch. Be the first to review it!
        </h3>
 </div>

app/views/pitches/_pitch.html.erb
<div class="container">
  <div class="row">
    <% @pitches.each do |pitch|  %>
      <div class="col col-xs-12 col-sm-4">
        <div class="card">
          <div class="card-image" style="background-image: url('<%= pitch.photo.url.nil? ? (pitch_photo(pitch)) : (cl_image_path pitch.photo)  %>')">
          </div>
          <div class="post-content">
            <h1 class=" title"> <%= pitch.name  %></h1>
            <h2 class="sub_title "> <%= pitch.topic  %>
              <h3 class="sub_title"> <%= pitch.target %> </h3>
            </h2>
            <span class="timestamp">
              <i class="fa fa-clock"></i>
            <%=  pitch.duration %> min. | <%=  pitch.created_at.strftime("%b %d, %Y") %>
           </span>
            <span class="comments">
              <i class="fa fa-comments">
               <%= pitch.feedbacks.count %> feedbacks </i>
            </span>
            <div class="space text-center">
              <%= link_to "Details",pitch_path(pitch), class: " btn-outline-primary " %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!--

            <div class="post-meta">
</div>

app/views/pitches/_video_description.html.erb
<% if @pitch.photo.present? %>
  <video width="100%" height="608" controls="controls" src=<%= cloudinary_url(@pitch.photo.filename.split("/")[1], :resource_type => :video) %> >
  </video>
<% else %>
  <video width="100%" height="608" controls="controls">
  </video>
<% end %>

app/views/pitches/edit.html.erb
<div class="text-center">
</div>

<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-sign-content">
    <h1>Do you want to perfect your pitch?</h1>
<div class="container">
 <div class="col-xs-12 col-sm-6 col-md-offset-1 col-md-4">
     <div class="pitchcard">
       <h2><strong> Improvement!</strong></h2>
        <div class="form-group">
          <%= simple_form_for @pitch do |f| %>
           <%= f.error_notification %>
          <div class="form-row">
             <div class="col-md-12">
                 <div class="col-md-12">
                 <%= f.input :name,
                  label: false,
                  required: true,
                  autofocus: true ,
                  placeholder: "Every great pitch needs a name!" %>
               </div>
              <div class="col-md-12">
                  <%= f.input :topic,
                    label: false,
                    required: true,
                    placeholder: "Topic" %>
                </div>
              <div class="col-md-12">
                 <%= f.input :duration,
                  label: false,
                  required: true,
                  placeholder: "How long is your pitch, in minutes" %>
               </div>
              <div class="col-md-12">
                  <%= f.input :target,
                  label: false,
                  required: true,
                  placeholder: "Who is your target audience?" %>
               </div>
             <div class="col-md-12">
                <%= f.input :transcript,
                  label: false,
                  as: :text,
                  required: true,
                  placeholder: "Copy & paste your pitch, here.",
                  :input_html => { 'rows' => 4, 'cols' => 10 } %>
              </div>
                <div class="form-actions">
              <%= f.button :submit, "Edit  pitch", class: "btn-primary" %>
            </div>
           </div>
         </div>
        <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/pitches/index.html.erb
<%= render 'pitches/pitch' %>

app/views/pitches/new.html.erb
<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-sign-content">
    <h1> Show me what you got</h1>
<div class="container">
 <div class="col-xs-12 col-sm-6 col-md-offset-1 col-md-4">
     <div class="pitchcard">
       <h2><strong>Define your pitch</strong></h2>
        <div class="form-group">
          <%= simple_form_for @pitch do |f| %>
           <%= f.error_notification %>
          <div class="form-row">
             <div class="col-md-12">
                 <%= f.input :name,
                  label: false,
                  required: true,
                  autofocus: true ,
                  placeholder: "Every great pitch needs a name!" %>
               </div>
              <div class="col-md-12">
                  <%= f.input :topic,
                    label: false,
                    required: true,
                    placeholder: "What are you talking about today?" %>
                </div>
              <div class="col-md-12">
                 <%= f.input :duration,
                  label: false,
                  required: true,
                  placeholder: "How many minutes do you have to pitch?" %>
               </div>
              <div class="col-md-12">
                  <%= f.input :target,
                  label: false,
                  required: true,
                  placeholder: "Who are you pitching to?" %>
               </div>
             <div class="col-md-12">
                <%= f.input :transcript,
                  label: false,
as: :text,
                  required: true,
                  placeholder: "Copy & paste your transcript, here if you have one.",
                  :input_html => { 'rows' => 4, 'cols' => 10 } %>
              </div>
                <div class="form-actions">
              <%= f.button :submit, "Create a pitch", class: "btn-primary" %>
            </div>
           </div>
         </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pitches/random.html.erb
<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-content">
    <h1><%= ['“Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.” —Norman Vincent Peale' , '“If you can dream it, you can do it.” —Walt Disney','“Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.” —George Whitefield', '“The future belongs to those who believe in the beauty of their dreams.” —Eleanor Roosevelt', '“Aim for the moon. If you miss, you may hit a star.” —W. Clement Stone', '“Don’t watch the clock; do what it does. Keep going.” —Sam Levenson', '“Keep your eyes on the stars, and your feet on the ground.” —Theodore Roosevelt', '“You just can’t beat the person who never gives up.” —Babe Ruth', '“Start where you are. Use what you have. Do what you can.” —Arthur Ashe', '“Why should you continue going after your dreams? Because seeing the look on the faces of the people who said you couldn’t… will be priceless.” —Kevin Ngo'].sample %></h1>

      <%= link_to 'Start Pitch',pitch_video_path(Pitch.find(params[:pitch_id])), class: "btn btn-lg  btn-primary center-block" %>
  </div>
</div>

app/views/pitches/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-sm-8">
      <%= render 'video_description' %>
    </div>
    <div class="col col-xs-12 col-sm-4">
      <div class="row">
        <div class="pitch-card">
          <%= cl_image_tag user_avatar(@pitch.user), class: "img-round" %>
          <%=  @pitch.user.first_name %>
          <%=  @pitch.user.last_name %>
        </div>
      </div>
      <div class="row">
        <div class="pitch-card">
         <h4 class="text-center">
          <%=  @pitch.name %>
         </h4>
         <div class="left">
           <h5 > About what?: <%=  @pitch.topic %> </h5>
           <h5 > To who?:  <%= @pitch.target %> </h5>
           <h6 > <%=  @pitch.duration %> min. | <%=  @pitch.created_at.strftime("%b %d, %Y") %></h6>
           <h6 > <%=  @pitch.transcript %></h6>
         </div>
         <div>
          <%= link_to 'Edit |',    edit_pitch_path(@pitch)  %>
          <%= link_to 'Delete', @pitch_path, method: :delete %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% if @pitch.feedbacks.any? %>
      <%= render 'pitches/feedback_present' %>
    <% else %>
      <%= render 'pitches/no_feedback' %>
    <% end %>
  </div>
  <div class="row">
    <div class="text-center ">
      <%= link_to "Add Feedback",new_pitch_feedback_path(@pitch), class: "btn btn-danger btn-lg"%>
    </div>
  </div>
</div>

app/views/pitches/video.html.erb
<div class="banner">
  <div class="banner-content">
    <!-- <video width="800" height="800" controls="controls">
    </video> -->
    <div class="DashboardContainer">
    </div>
  </div>
  <div class="flex-button" style="display: flex; flex-direction: column;">
    <marquee  scrollamount="1.3" behavior="scroll" direction="up" style="height:250px;width: 400px;color:black"><%= @pitch.transcript %></marquee>
    <div>
      <%#= simple_form_for(@pitch) do |f| %>
        <%#= f.input :photo %>
        <%#= f.input :photo_cache, as: :hidden %>
        <%#= f.button :submit %>
        <%# end %>
      </div>
      <div>
      </br>
      <%= link_to 'Submit',  pitches_path , class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>