config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :profile, to: 'users#profile'
  resources :pitches do
    get :video, to: 'pitches#video'
    get :random, to: 'pitches#random'
    resources :feedbacks, shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner-login.html.erb
<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-sign-content">
    <h1> Happy to see you again </h1>
    <%= render 'shared/form-login' %>
  </div>
</div>

app/views/shared/_banner-sign.html.erb
<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-sign-content">
    <h1>30 seconds away from a better you</h1>
    <%= render 'shared/form-signin' %>
    </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image:
linear-gradient(-225deg, rgba(189,194,197,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.png' %>);">
  <div class="banner-content">
    <h1> The way you pitch. We perfect it.</h1>
    <div >
       <% if user_signed_in? %>

       <%= link_to 'Pitch Now', new_pitch_path,class: "btn btn-lg  btn-primary " %>
       <% else  %>
       <%= link_to 'Pitch Now',new_user_session_path, class: "btn btn-lg  btn-primary " %>
      <% end %>
        <%= link_to 'Explore!', pitches_path, class: "btn btn-lg  btn-primary change " %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
  <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <ul class="list-inline">
              <li><a href=""><i class="fab fa-youtube"></i></a></li>
              <li><a href=""><i class="fab fa-instagram"></i></a></li>
              <li><a href=""><i class="fab fa-facebook"></i></a></li>
              <li><a href=""><i class="fab fa-twitter"></i></a></li>
            </ul>
          </div>
          <div class="col-xs-8 text-right">
            <p>Team PitchPerfect</p>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_form-login.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-6 col-md-offset-1 col-md-4">
     <div class="logincard">
       <h2><strong>Log In</strong></h2>
        <div class="form-group">
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= f.error_notification %>
            <div class="form-row">
               <div class="col-md-12">
                 <%= f.input :email,
                            label: false,
                            required: false,
                            autofocus: true,
                            placeholder: "Email",
                            input_html: { autocomplete: "email" } %>
                </div>


              <div class="col-md-12">
                <%= f.input :password,
                            label: false,
                            placeholder: "Password",
                            required: false,
                            input_html: { autocomplete: "current-password" } %>
                <%= f.input :remember_me, label_html: { id: "remember"}, as: :boolean if devise_mapping.rememberable?  %>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Log in",  class: "btn-primary"  %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_form-signin.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-6 col-md-offset-1 col-md-4">
     <div class="petitecard">
      <h2><strong>Sign up</strong></h2>
     <div class="form-group">
     <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
     <%= f.error_notification %>
<div class="form-row">
  <div class="col-md-6">
 <%= f.input :first_name,
 label: false,
                required: true,
                autofocus: true ,
                placeholder: "First Name" %>

                  </div>

<div class="col-md-6">
 <%= f.input :last_name,
                label: false,
                required: true,
                autofocus: true ,
                placeholder: "Last name" %>
  </div>
   <div class="col-md-12">
   <%= f.input :email,
                required: true,
                label: false,
                autofocus: true ,
                placeholder: "gab@gmail.com" %>

                    <%= f.input :password,
                 label: false,
                required: true,
                placeholder: "Password (6 characters minimum)",



                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                 label: false,
                 placeholder: "Confirm your password",
                required: true,
                input_html: { autocomplete: "new-password" } %>
                </div>
</div>




  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up", class: "btn-primary" %>
  </div>
<% end %>

        </div>
      </div>
    </div>